apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
  labels:
    app: nginx
    nginx/version: "1.0"
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: "nginx-service"
              servicePort: 80

