apiVersion: v1
data:
  mapRoles: |-
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::482720962971:role/eks-node-group-role
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::482720962971:role/cluster_admin
      username: cluster_admin
    - groups:
      - system:masters
      rolearn: arn:aws:iam::482720962971:role/jenkins_role
      username: jenkins_role
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
